apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  selector:
    matchLabels:
      app: cloudflared
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --no-autoupdate
        - run
        - --token
        - eyJhIjoiMjcwNGQ2NTllNzgzYjBmYjViY2ZkNzZiZDVkYTA0NTQiLCJ0IjoiNTU3MDhiMjgtZTgwZC00ZTViLTgwYjctY2NmNWZjYzk4OTg4IiwicyI6Ik1tVTNNVGt4WkRndE5HRmtOUzAwTXprMkxUazFORGd0WlRNeVlXVmhNVFV3T1RKayJ9