apiVersion: apps/v1
kind: Deployment
metadata:
  name: umami
spec:
  replicas: 1
  selector:
    matchLabels:
      app: umami
  template:
    metadata:
      labels:
        app: umami
    spec:
      containers:
      - name: umami
        image: ghcr.io/umami-software/umami:postgresql-latest
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_URL
          value: ${UMAMI_DATABASE_URL}
        - name: APP_SECRET
          value: ${UMAMI_APP_SECRET}
---
apiVersion: v1
kind: Service
metadata:
  name: umami-service
spec:
  selector:
    app: umami
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000